### ISSUE TITLE
Iceweasel support

### ISSUE THREAD

**Issue by Perlence** [cyberscorpio/superstart#64]
Hello. Thank you for very nice addon. Unfortunately it doesn't work in Iceweasel out of the box: `Super Start is incompatible with Iceweasel 31.4.0`.

**Comment by ncelerier** [comment]
Hello, one workaround to this might be to modify that line:
 `<em:minVersion>32.0</em:minVersion>`

From this file : 
https://github.com/cyberscorpio/superstart/blob/master/xpi/install.rdf

You can do it on your computer directly : just find the xpi in your Firefox profile, open it with something like 7zip, find the install.rdf file, copy it somewhere, change the minVersion to 31.0 and replace the original install.rdf with the one you modified. 

I've already had that kind of problem with other extensions and it has worked. It might not work if something has changed in Firefox though.

**Comment by Perlence** [comment]
That did the trick, thank you.
